FROM openjdk:8u181-alpine

# https://spring.io/guides/gs/spring-boot-docker/
VOLUME /tmp
COPY target/*.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

EXPOSE 8080 8082
HEALTHCHECK --interval=1m --timeout=5s \
CMD curl -f http://localhost:8080/health || exit 1
