apiVersion: v1
kind: Service
metadata:
  name: notejam-svc
  labels:
    app: notejam
spec:
  type: NodePort
  selector:
    app: notejam
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 30007
